<a href="https://colab.research.google.com/github/njsuriya/ML_clf_algorithms/blob/main/CountVectorizer_TFIDFVectorizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**COUNT VECTORIZER**

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
documents = ["Jeyasuriya is from Madurai district", 
             "Madurai is in TamilNadu state. Madurai is known as temple city ", 
             "He was born and studied in his native place Madurai"]

In [3]:
cv = CountVectorizer()
cv_removedstop = CountVectorizer(stop_words='english')

In [4]:
documents_cv = cv.fit_transform(documents)

In [5]:
cv.get_feature_names_out()

array(['and', 'as', 'born', 'city', 'district', 'from', 'he', 'his', 'in',
       'is', 'jeyasuriya', 'known', 'madurai', 'native', 'place', 'state',
       'studied', 'tamilnadu', 'temple', 'was'], dtype=object)

In [6]:
documents_cv

<3x20 sparse matrix of type '<class 'numpy.int64'>'
	with 24 stored elements in Compressed Sparse Row format>

In [7]:
documents_cv.toarray()

array([[0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 1, 2, 0, 1, 2, 0, 0, 1, 0, 1, 1, 0],
       [1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1]])

In [8]:
documents_cv_removedstop = cv_removedstop.fit_transform(documents)

In [9]:
cv_removedstop.get_feature_names_out()

array(['born', 'city', 'district', 'jeyasuriya', 'known', 'madurai',
       'native', 'place', 'state', 'studied', 'tamilnadu', 'temple'],
      dtype=object)

In [10]:
documents_cv_removedstop.toarray()

array([[0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 2, 0, 0, 1, 0, 1, 1],
       [1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0]])

In [11]:
cv_ngram_notstop = CountVectorizer(ngram_range=(2,2))
cv_ngram_notstop.fit(documents)
doc_cv_ngram_notstop = cv_ngram_notstop.transform(documents)
cv_ngram_notstop.get_feature_names_out()

array(['and studied', 'as temple', 'born and', 'from madurai', 'he was',
       'his native', 'in his', 'in tamilnadu', 'is from', 'is in',
       'is known', 'jeyasuriya is', 'known as', 'madurai district',
       'madurai is', 'native place', 'place madurai', 'state madurai',
       'studied in', 'tamilnadu state', 'temple city', 'was born'],
      dtype=object)

In [12]:
doc_cv_ngram_notstop

<3x22 sparse matrix of type '<class 'numpy.int64'>'
	with 22 stored elements in Compressed Sparse Row format>

In [13]:
doc_cv_ngram_notstop.toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 2, 0, 0, 1, 0, 1, 1, 0],
       [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1]])

***fit() method used to get the parameters(mean , variance for Standard Scalar | Unique words (vocabulary ) & frequency for Count vectorizer..) transform method will apply the above params to the data features and forms the scaled features (Document Term Matrix for TFIDF and CV )***

---

fit_transform is used in the train set , transform is used in the test set (because exposing the test set to the train model as new )

**TFIDF VECTORIZER**

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [25]:
doc = ["Suriya,Suriya How are you? How about your life?", "Are you still located in Madurai?", " Is you company located in Madurai? I'll come to Madurai to see you"]

In [26]:
tfidf = TfidfVectorizer()

In [27]:
tfidf.fit(doc)

TfidfVectorizer()

In [28]:
doc_tfidf = tfidf.transform(doc)

In [29]:
tfidf.get_feature_names_out()

array(['about', 'are', 'come', 'company', 'how', 'in', 'is', 'life', 'll',
       'located', 'madurai', 'see', 'still', 'suriya', 'to', 'you',
       'your'], dtype=object)

In [30]:
doc_tfidf

<3x17 sparse matrix of type '<class 'numpy.float64'>'
	with 23 stored elements in Compressed Sparse Row format>

In [31]:
#The document Term matrix probability will increase if same vocabulary occurs in document multiple times 

doc_tfidf.toarray()

array([[0.28955446, 0.22021363, 0.        , 0.        , 0.57910892,
        0.        , 0.        , 0.28955446, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.57910892, 0.        ,
        0.17101553, 0.28955446],
       [0.        , 0.39740155, 0.        , 0.        , 0.        ,
        0.39740155, 0.        , 0.        , 0.        , 0.39740155,
        0.39740155, 0.        , 0.52253528, 0.        , 0.        ,
        0.30861775, 0.        ],
       [0.        , 0.        , 0.26855238, 0.26855238, 0.        ,
        0.20424101, 0.26855238, 0.        , 0.26855238, 0.20424101,
        0.40848201, 0.26855238, 0.        , 0.        , 0.53710476,
        0.31722272, 0.        ]])